# Identification
sonar.projectKey=JavierSanabriaMiranda_Graphite
sonar.organization=javiersanabriamiranda
sonar.host.url=https://sonarcloud.io

# Code
sonar.sources=front/src

# Exclusions (not analyzed)
sonar.exclusions=tauri/**, node_modules/**, dist/**, public/**, src/data/**, src/assets/fonts/**

# Test coverage
# Where Vitest left the LCOV report for coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8