# Identification
sonar.projectKey=JavierSanabriaMiranda_Graphite
sonar.organization=javiersanabriamiranda
sonar.host.url=https://sonarcloud.io

# Code
sonar.sources=front/src
sonar.tests=front/src

# Exclusions (not analyzed)
sonar.exclusions=tauri/**, **/*.test.jsx, **/*.spec.jsx, node_modules/**, dist/**, public/**, front/src/data/**, front/src/assets/**, front/src/services/db/pre_designed_pages/**

sonar.tests.inclusion=**/*.test.jsx,**/*.spec.jsx

# Test coverage
# Where Vitest left the LCOV report for coverage
sonar.javascript.lcov.reportPaths=front/coverage/lcov.info
sonar.testExecutionReportPaths=front/test-report.xml

sonar.sourceEncoding=UTF-8